### ISSUE TITLE
Undefined method `delete_prefix' for ruby 2.4.10-alpine in gitlab pipeline

### ISSUE THREAD

**Issue by DenisDenis9331** [prontolabs/pronto#463]
Problem: pronto not work in gitlab pipeline with ruby 2.4.10-alpine

Dockerfile:
```
FROM ruby:2.4.10-alpine

WORKDIR /usr/src/config/

COPY Gemfile ./ 
COPY rules ./rules

RUN apk add --no-cache \
  git \
  openssl-dev \
  alpine-sdk \
  cmake \
  g++ \
  nodejs \
  coreutils \
  && gem update --system 3.2.3 \
  && gem install bundler -v 2.3.27 \
  && bundle install

WORKDIR /usr/src/app/

RUN chown 107:114 -R /usr/src/app/

CMD ["sh"]
```

Gemfile:
```
source 'https://rubygems.org'

gem 'rugged', '1.6.3' # Fix https://github.com/prontolabs/pronto/issues/447
gem 'pronto', '0.11.2'
gem 'pronto-rubocop'
gem 'pronto-flay'
gem 'pronto-coffeelint'
gem 'pronto-jshint'
gem 'execjs'
gem 'pronto-haml'
gem 'pronto-scss'
gem 'faraday-retry'
```

.gitlab-ci.yml:
```
variables:
  DOCKER_IMAGE: "image_name"
  GIT_STRATEGY: clone
  GIT_DEPTH: 0

stages:
 - linter

pronto:
  stage: linter
  only:
    - merge_requests
  script:
    - >
       if echo "$CI_MERGE_REQUEST_TITLE" | grep -q "\[skip linter\]"; then
         echo "Skipping linter due to [skip linter] tag in merge request title"
         exit 0
       fi
    - docker pull $DOCKER_IMAGE
    - >
       docker run --rm
       -u $(id -u gitlab-runner):$(id -g gitlab-runner)
       -e "HOME=/usr/src/app"
       -e "PRONTO_GITLAB_API_ENDPOINT=https://gitlab.blabla.com/api/v4"
       -e "PRONTO_GITLAB_API_PRIVATE_TOKEN=$PRONTO_ACCESS_TOKEN"
       -e "PRONTO_PULL_REQUEST_ID=$CI_MERGE_REQUEST_IID"
       -v $(pwd):/usr/src/app $DOCKER_IMAGE
       sh -c "
       find /usr/src/config/rules/ -maxdepth 1 -type f -exec cp -t . {} + &&
       pronto run -c origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME -f gitlab_mr --exit-code
       "
```

.pronto.yml:
```
all:
  exclude:
    - 'spec/**/*'

max_warnings: 60
warnings_per_review: 30
verbose: false
runners:
  - rubocop
  - haml
  - scss
  - flay
  - coffeelint
  - jshint
skip_runners: []
```

Error in gitlab pipeline:
```
$ docker run --rm -u $(id -u gitlab-runner):$(id -g gitlab-runner) -e "HOME=/usr/src/app" -e "PRONTO_GITLAB_API_ENDPOINT=https://gitlab.blabla.com/api/v4" -e "PRONTO_GITLAB_API_PRIVATE_TOKEN=$PRONTO_ACCESS_TOKEN" -e "PRONTO_PULL_REQUEST_ID=$CI_MERGE_REQUEST_IID" -v $(pwd):/usr/src/app $DOCKER_IMAGE sh -c " find /usr/src/config/rules/ -maxdepth 1 -type f -exec cp -t . {} + && pronto run -c origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME -f gitlab_mr --exit-code "
/usr/local/bundle/gems/path_expander-1.1.2/lib/path_expander.rb:58:in `block in expand_dirs_to_files': undefined method `delete_prefix' for #<Pathname:0x0000562e718b4c78> (NoMethodError)
	from /usr/local/bundle/gems/path_expander-1.1.2/lib/path_expander.rb:58:in `map'
	from /usr/local/bundle/gems/path_expander-1.1.2/lib/path_expander.rb:58:in `expand_dirs_to_files'
	from /usr/local/bundle/gems/path_expander-1.1.2/lib/path_expander.rb:113:in `block in process_args'
	from /usr/local/bundle/gems/path_expander-1.1.2/lib/path_expander.rb:95:in `each'
	from /usr/local/bundle/gems/path_expander-1.1.2/lib/path_expander.rb:95:in `process_args'
	from /usr/local/bundle/gems/path_expander-1.1.2/lib/path_expander.rb:147:in `process'
	from /usr/local/bundle/gems/flay-2.13.3/lib/flay.rb:26:in `run'
	from /usr/local/bundle/gems/pronto-flay-0.11.1/lib/pronto/flay.rb:25:in `flay'
	from /usr/local/bundle/gems/pronto-flay-0.11.1/lib/pronto/flay.rb:13:in `run'
	from /usr/local/bundle/gems/pronto-0.11.2/lib/pronto/runners.rb:20:in `block in run'
	from /usr/local/bundle/gems/pronto-0.11.2/lib/pronto/runners.rb:13:in `each'
	from /usr/local/bundle/gems/pronto-0.11.2/lib/pronto/runners.rb:13:in `run'
	from /usr/local/bundle/gems/pronto-0.11.2/lib/pronto.rb:66:in `run'
	from /usr/local/bundle/gems/pronto-0.11.2/lib/pronto/cli.rb:70:in `block in run'
	from /usr/local/bundle/gems/pronto-0.11.2/lib/pronto/cli.rb:68:in `chdir'
	from /usr/local/bundle/gems/pronto-0.11.2/lib/pronto/cli.rb:68:in `run'
	from /usr/local/bundle/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
	from /usr/local/bundle/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
	from /usr/local/bundle/gems/pronto-0.11.2/bin/pronto:6:in `<top (required)>'
	from /usr/local/bundle/bin/pronto:23:in `load'
	from /usr/local/bundle/bin/pronto:23:in `<main>'
Cleaning up project directory and file based variables 00:00
ERROR: Job failed: exit status 1
```
